# Generated by Django 5.0.1 on 2024-01-31 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер класса должен быть не менее 1.'), django.core.validators.MaxValueValidator(11, message='Номер класса должен быть не более 11.')], verbose_name='Номер класса')),
                ('class_letter', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(code='invalid_class_letter', message='Введите одну кириллическую букву.', regex='^[а-я]$')], verbose_name='Буква класса')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оценки')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не менее 1.'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не более 5.')], verbose_name='Оценка')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.event', verbose_name='Мероприятие')),
                ('schoolclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.schoolclass', verbose_name='Класс')),
            ],
        ),
    ]
